Changes in SN omnia_service_node script

diff --git a/discovery/roles/postscripts/common/templates/omnia_service_node.j2 b/discovery/roles/postscripts/common/templates/omnia_service_node.j2
--- a/discovery/roles/postscripts/common/templates/omnia_service_node.j2
+++ b/discovery/roles/postscripts/common/templates/omnia_service_node.j2
@@ -60,8 +60,8 @@ if [ "$str_os_type" = "redhat" ]; then
     sudo dnf install -y podman
 fi
 
-sudo systemctl enable podman.socket
-sudo systemctl start podman.socket
+sudo systemctl enable podman.socket || { echo "Error enabling podman.socket." >> "$LOGFILE"; exit 1; }
+sudo systemctl start podman.socket || { echo "Error starting podman.socket." >> "$LOGFILE"; exit 1; }
 
 {% if omnia_share_option == "NFS" %}
 # Create omnia_path directory if it does not exist
