Update to oim ha node postbootscript and omnia service monitoring removal as it is now in the container image

diff --git a/discovery/roles/postscripts/common/templates/omnia_oim_ha_node.j2 b/discovery/roles/postscripts/common/templates/omnia_oim_ha_node.j2
--- a/discovery/roles/postscripts/common/templates/omnia_oim_ha_node.j2
+++ b/discovery/roles/postscripts/common/templates/omnia_oim_ha_node.j2
@@ -1,8 +1,7 @@
 #!/bin/bash
 ################################################################################################################
-#  omnia_pcs_setup:
-#      Configure Omnia's pcs container on HA OIM nodes
-#
+#  omnia_oim_ha_node:
+#      Configure a passive OIM node.
 #################################################################################################################
 # Define log file
 LOGFILE="/var/log/omnia/pcs_setup.log"
@@ -71,10 +70,10 @@ echo "{{ nfs_server_ip }}:{{ nfs_server_share_path }} {{ oim_shared_path }} nfs 
 podman load -i {{ container_images_path }} || { echo "Error loading container images." >> "$LOGFILE"; exit 1; }
 
 # Ensure the management interface name is the same as active OIM, if not add the active OIM's interface name as an alternative name
-if ! ifconfig | grep -w {{ managment_admin_nic }}; then
+if ! ifconfig | grep -w {{ hostvars['omnia_provision']['admin_nic'] }}; then
     passive_oim_node_ips={{ hostvars['omnia_provision']['passive_oim_nodes'].query_result | map(attribute='admin_ip') | join(' ') }}
     for admin_ip in ${passive_oim_node_ips};do 
-        INTERFACE=$(ip addr show | awk '/${admin_ip}/{print $NF; exit}')
+        INTERFACE=$(ip addr show | awk "/${admin_ip}/{print \$NF; exit}")
         if [ -n "$INTERFACE" ]; then
             break
         fi
@@ -83,22 +82,12 @@ if ! ifconfig | grep -w {{ managment_admin_nic }}; then
     if [ -z "$INTERFACE" ]; then
         echo "Error: No admin interface found." >> "$LOGFILE"
         exit 1
-
-    ADMIN_MAC=$(ip link show ${INTERFACE} | awk '/ether/{print $2}')
-
-    if [ -z "$ADMIN_MAC" ]; then
-        echo "Error: No admin MAC address found." >> "$LOGFILE"
-        exit 1
-
-    ip link set ${INTERFACE} name {{ managment_admin_nic }} || { echo "Error renaming admin interface." >> "$LOGFILE"; exit 1; }
-    mkdir -p /etc/systemd/network/ || { echo "Error creating systemd network directory." >> "$LOGFILE"; exit 1; }
-    cp /usr/lib/systemd/network/99-default.link {{ systemd_link_file}} || { echo "Error copying link file." >> "$LOGFILE"; exit 1; }
-    sed -i "/\[Match\]/a MACAddress=${ADMIN_MAC}" {{ systemd_link_file}} || { echo "Error adding MACAddress." >> "$LOGFILE"; exit 1; }
-    sed -i "/\[Link\]/a AlternativeNames={{ managment_admin_nic }}" {{ systemd_link_file}} || { echo "Error adding admin NIC AlternativeNames." >> "$LOGFILE"; exit 1; }
-    dracut -f || { echo "Error running dracut." >> "$LOGFILE"; exit 1; }
+    fi
+    ip link set ${INTERFACE} name {{ hostvars['omnia_provision']['admin_nic'] }} || { echo "Error: re-naming admin interface." >> "$LOGFILE"; } 
 fi
 
-# Start the pcs container
-sudo sudo systemctl start omnia_pcs || { echo "Error starting omnia_pcs service." >> "$LOGFILE"; exit 1; }
+# Enable and start the pcs container
+sudo systemctl enable omnia_pcs || { echo "Error enabling omnia_pcs service." >> "$LOGFILE"; exit 1; }
+sudo systemctl start omnia_pcs || { echo "Error starting omnia_pcs service." >> "$LOGFILE"; exit 1; }
 echo "$(date) - INFO - Finished OIM Passive node setup." >> "$LOGFILE"
 echo "---------------------------"
