Updates to admin nic syncing for oim passive nodes

diff --git a/discovery/roles/postscripts/common/templates/omnia_pcs_setup.j2 b/discovery/roles/postscripts/common/templates/omnia_pcs_setup.j2
--- a/discovery/roles/postscripts/common/templates/omnia_pcs_setup.j2
+++ b/discovery/roles/postscripts/common/templates/omnia_pcs_setup.j2
@@ -21,7 +21,7 @@ if [ ! -f "$LOGFILE" ]; then
 fi
 
 echo "--------------------------" >> "$LOGFILE"
-echo "$(date) - INFO - Starting OIM Passive node setup" >> "$LOGFILE"
+echo "$(date) - INFO - Starting OIM Passive node setup." >> "$LOGFILE"
 
 if [ -f "/etc/debian_version" ];then
   str_os_type="debian"
@@ -34,8 +34,9 @@ if [ "$str_os_type" = "redhat" ]; then
     sudo dnf install -y podman
 fi
 
-sudo systemctl enable podman.socket
-sudo systemctl start podman.socket
+# Enable and start podman.socket
+sudo systemctl enable podman.socket || { echo "Error enabling podman.socket." >> "$LOGFILE"; exit 1; }
+sudo systemctl start podman.socket || { echo "Error starting podman.socket." >> "$LOGFILE"; exit 1; }
 
 {% if omnia_share_option == "NFS" %}
 # Create omnia_path directory if it does not exist
@@ -43,7 +44,7 @@ echo "Creating omnia shared path directory if it does not exist" >> "$LOGFILE"
 mkdir -p {{ oim_shared_path }}
 
 # Validate if NFS server is reachable
-echo "Validating if NFS server is reachable" >> "$LOGFILE"
+echo "Validating if NFS server is reachable." >> "$LOGFILE"
 ping -c1 -W1 {{ nfs_server_ip }} > /dev/null
 if [ $? -ne 0 ]; then
     echo -e "NFS server {{ nfs_server_ip }} is not reachable." >> "$LOGFILE"
@@ -51,15 +52,15 @@ if [ $? -ne 0 ]; then
 fi
 
 # Mount NFS server share path in Omnia share path
-echo "Mounting NFS server share path in Omnia share path" >> "$LOGFILE"
+echo "Mounting NFS server share path in Omnia share path." >> "$LOGFILE"
 mount -t nfs -o nosuid,rw,sync,hard,intr,timeo=30 {{ nfs_server_ip }}:{{ nfs_server_share_path }} {{ oim_shared_path }}
 
 # Validate if NFS server share path is mounted
-echo "Validating if NFS server share path is mounted" >> "$LOGFILE"
+echo "Validating if NFS server share path is mounted." >> "$LOGFILE"
 if grep -qs "{{ nfs_server_ip }}:{{ nfs_server_share_path }}" /proc/mounts; then
     echo -e "NFS server share path is mounted." >> "$LOGFILE"
 else
-    echo -e "NFS server share path is not mounted. Provide valid NFS server details" >> "$LOGFILE"
+    echo -e "NFS server share path is not mounted. Provide valid NFS server details." >> "$LOGFILE"
     exit 1
 fi
 
@@ -67,8 +68,37 @@ fi
 echo "{{ nfs_server_ip }}:{{ nfs_server_share_path }} {{ oim_shared_path }} nfs nosuid,rw,sync,hard,intr" >> /etc/fstab
 {% endif %}
 
-podman load -i {{ container_images_path }}
+podman load -i {{ container_images_path }} || { echo "Error loading container images." >> "$LOGFILE"; exit 1; }
+
+# Ensure the management interface name is the same as active OIM, if not add the active OIM's interface name as an alternative name
+if ! ifconfig | grep -w {{ managment_admin_nic }}; then
+    passive_oim_node_ips={{ hostvars['omnia_provision']['passive_oim_nodes'].query_result | map(attribute='admin_ip') | join(' ') }}
+    for admin_ip in ${passive_oim_node_ips};do 
+        INTERFACE=$(ip addr show | awk '/${admin_ip}/{print $NF; exit}')
+        if [ -n "$INTERFACE" ]; then
+            break
+        fi
+    done
+
+    if [ -z "$INTERFACE" ]; then
+        echo "Error: No admin interface found." >> "$LOGFILE"
+        exit 1
+
+    ADMIN_MAC=$(ip link show ${INTERFACE} | awk '/ether/{print $2}')
+
+    if [ -z "$ADMIN_MAC" ]; then
+        echo "Error: No admin MAC address found." >> "$LOGFILE"
+        exit 1
+
+    ip link set ${INTERFACE} name {{ managment_admin_nic }} || { echo "Error renaming admin interface." >> "$LOGFILE"; exit 1; }
+    mkdir -p /etc/systemd/network/ || { echo "Error creating systemd network directory." >> "$LOGFILE"; exit 1; }
+    cp /usr/lib/systemd/network/99-default.link {{ systemd_link_file}} || { echo "Error copying link file." >> "$LOGFILE"; exit 1; }
+    sed -i "/\[Match\]/a MACAddress=${ADMIN_MAC}" {{ systemd_link_file}} || { echo "Error adding MACAddress." >> "$LOGFILE"; exit 1; }
+    sed -i "/\[Link\]/a AlternativeNames={{ managment_admin_nic }}" {{ systemd_link_file}} || { echo "Error adding admin NIC AlternativeNames." >> "$LOGFILE"; exit 1; }
+    dracut -f || { echo "Error running dracut." >> "$LOGFILE"; exit 1; }
+fi
+
 # Start the pcs container
-sudo sudo systemctl start omnia_pcs
-echo "$(date) - INFO - Finished OIM Passive node setup" >> "$LOGFILE"
+sudo sudo systemctl start omnia_pcs || { echo "Error starting omnia_pcs service." >> "$LOGFILE"; exit 1; }
+echo "$(date) - INFO - Finished OIM Passive node setup." >> "$LOGFILE"
 echo "---------------------------"
