[deepspeed fix]
Signed-off-by: pranav_kumar5 <pranav.kumar6@dell.com>

diff --git a/examples/ai_examples/intel/deepSpeed/ds_configuration.yml b/examples/ai_examples/intel/deepSpeed/ds_configuration.yml
--- a/examples/ai_examples/intel/deepSpeed/ds_configuration.yml
+++ b/examples/ai_examples/intel/deepSpeed/ds_configuration.yml
@@ -2,7 +2,7 @@
 apiVersion: kubeflow.org/v2beta1
 kind: MPIJob
 metadata:
-  name: gaudi-llm-ds-ft
+  name: gaudi-llm-ds-ft-multi-8b
   namespace: workloads
 spec:
   slotsPerWorker: 8
@@ -15,18 +15,18 @@ spec:
         spec:
           containers:
             - image: vault.habana.ai/gaudi-docker/1.19.2/ubuntu24.04/habanalabs/pytorch-installer-2.5.1:latest
-              name: gaudi-llm-ds-ft-launcher
+              name: gaudi-llm-ds-ft-multi-8b-launcher
               env:
                 - name: HF_HOME
-                  value: /storage/huggingface
+                  value: "/root/.cache/huggingface"
                 - name: http_proxy
                   value: ""
                 - name: https_proxy
                   value: ""
                 - name: no_proxy
-                  value: "127.0.0.1,localhost"
+                  value: "localhost,127.0.0.1"
                 - name: LLM_MODEL
-                  value: "meta-llama/Meta-Llama-3.1-8B-Instruct"
+                  value: meta-llama/Meta-Llama-3.1-8B-Instruct
                 - name: NUM_HPU
                   value: "8"
                 - name: NUM_EPOCHS
@@ -39,6 +39,24 @@ spec:
                   /usr/bin/ssh-keygen -A;
                   echo "    KexAlgorithms curve25519-sha256,sntrup761x25519-sha512@openssh.com" |  tee -a /etc/ssh/ssh_config;
                   /usr/sbin/sshd;
+
+                  retry_until_success() {
+                       local command='$@';
+                       local attempt=1;
+
+                       while true; do
+                           echo "Attempt $attempt";
+                           eval $command;
+                           if [ $? -eq 0 ]; then
+                               echo "Command succeeded on attempt $attempt.";
+                               break;
+                           else
+                               echo "Command failed on attempt $attempt. Retrying...";
+                               attempt=$((attempt + 1));
+                               sleep 1;  # Optional: Add a delay between retries
+                           fi;
+                       done;
+                  };
                   HOSTSFILE=$OMPI_MCA_orte_default_hostfile;
                   MASTER_ADDR="$(head -n 1 $HOSTSFILE | sed -n s/[[:space:]]slots.*//p)";
                   SETUP_CMD="git clone  https://github.com/huggingface/optimum-habana /optimum-habana";
@@ -50,22 +68,44 @@ spec:
                   cd /optimum-habana;
                   git checkout v1.15.0;
                   sed -i '194s|deepspeed|deepspeed --force_multi|' optimum/habana/distributed/distributed_runner.py;
-                  pip install .;
-                  pip install -r examples/language-modeling/requirements.txt;
-                  pip install git+https://github.com/HabanaAI/DeepSpeed.git@1.19.0;
+                  retry_until_success pip install .;
+                  retry_until_success pip install -r examples/language-modeling/requirements.txt;
+                  retry_until_success pip install git+https://github.com/HabanaAI/DeepSpeed.git@1.19.0;
 
                   mpirun --npernode 1 \
                     --tag-output \
                     --allow-run-as-root \
                     --prefix $MPI_ROOT \
+                    -x no_proxy=$no_proxy \
                     -x http_proxy=$http_proxy \
                     -x https_proxy=$https_proxy \
-                    -x no_proxy=$no_proxy \
                     -x LLM_MODEL=$LLM_MODEL \
                     -x HF_HOME=$HF_HOME \
                     -x NUM_HPU=$NUM_HPU \
                     -x HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN \
                     bash -i -c '
+
+                    # Define the retry function
+                    retry_until_success() {
+                        local cmd="$@"
+                        local max_retries=5  # Number of retries
+                        local delay=5        # Delay between retries in seconds
+
+                        for ((i=1; i<=max_retries; i++)); do
+                            echo "Attempt $i: $cmd"
+                            if $cmd; then
+                                echo "Success!"
+                                return 0
+                            else
+                                echo "Command failed. Retrying in $delay seconds..."
+                                sleep $delay
+                            fi
+                        done
+
+                        echo "Command failed after $max_retries attempts."
+                        return 1
+                    }
+
                     git clone  https://github.com/huggingface/optimum-habana /optimum-habana
                     cd /optimum-habana
                     git checkout v1.15.0
@@ -74,18 +114,20 @@ spec:
                     https_var="os.environ[\"https_proxy\"] = \"${https_proxy}\""
                     http_var="os.environ[\"http_proxy\"] = \"${http_proxy}\""
                     no_proxy_var="os.environ[\"no_proxy\"] = \"${no_proxy}\""
-
-                    sed -i "56i\\${hf_home_var}" examples/language-modeling/run_lora_clm.py
-                    sed -i "57i\\${token_var}" examples/language-modeling/run_lora_clm.py
-                    sed -i "58i\\${no_proxy_var}" examples/language-modeling/run_lora_clm.py
-                    pip install .
-                    pip install -r examples/language-modeling/requirements.txt
-                    pip install git+https://github.com/HabanaAI/DeepSpeed.git@1.19.0
+                    sed -i "56i\\${https_var}" examples/language-modeling/run_lora_clm.py
+                    sed -i "57i\\${http_var}" examples/language-modeling/run_lora_clm.py
+                    sed -i "58i\\${hf_home_var}" examples/language-modeling/run_lora_clm.py
+                    sed -i "59i\\${token_var}" examples/language-modeling/run_lora_clm.py
+                    sed -i "60i\\${no_proxy_var}" examples/language-modeling/run_lora_clm.py
+                    retry_until_success pip install .
+                    retry_until_success pip install -r examples/language-modeling/requirements.txt
+                    retry_until_success pip install git+https://github.com/HabanaAI/DeepSpeed.git@1.19.0
                     ';
 
-                    cd /optimum-habana/examples/language-modeling/;
                     eval $(ssh-agent);
                     ssh-add;
+
+                    cd /optimum-habana/examples/language-modeling/;
                     python3 ../gaudi_spawn.py --hostfile=$HOSTSFILE --use_deepspeed --world_size $N_CARDS  run_lora_clm.py --model_name_or_path $LLM_MODEL \
                     --dataset_name tatsu-lab/alpaca \
                     --bf16 True \
@@ -118,7 +160,7 @@ spec:
 
               volumeMounts:
                 - name: datasets
-                  mountPath: /storage
+                  mountPath: /root/.cache
           volumes:
             - name: datasets
               persistentVolumeClaim:
@@ -131,7 +173,13 @@ spec:
           hostIPC: true
           containers:
             - image: vault.habana.ai/gaudi-docker/1.19.2/ubuntu24.04/habanalabs/pytorch-installer-2.5.1:latest
-              name: gaudi-llm-ds-ft-worker
+              name: gaudi-llm-ds-ft-multi-8b-worker
+              command: ["/bin/bash", "-c"]
+              args:
+                - >-
+                  /usr/bin/ssh-keygen -A;
+                  /usr/sbin/sshd;
+                  sleep 365d;
               resources:
                 limits:
                   habana.ai/gaudi: 8
@@ -143,13 +191,7 @@ spec:
                   hugepages-2Mi: 312600Mi
               volumeMounts:
                 - name: datasets
-                  mountPath: /storage
-              command: ["/bin/bash", "-c"]
-              args:
-                - >-
-                    /usr/bin/ssh-keygen -A;
-                    /usr/sbin/sshd;
-                    sleep 365d;
+                  mountPath: /root/.cache
           volumes:
             - name: datasets
               persistentVolumeClaim:
